# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s = "Hi there Sam!"
a=s.split()
print(a[0])
print(a[1])
print(a[2])

Hi
there
Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
a=d['k1']
b=a[3]
c=b['tricky']
e=c[3]
f=e['target']
g=f[3]
print(g)

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10,dtype=int)*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
a=np.arange(0,9,1)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=[a]+[b]
c

[array([1, 2, 3]), array([4, 5, 6])]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
d={'Name':['Vivek','Max'],'Age':['22','44'],'Salary':[30000,60000]}
d
df=pd.DataFrame(d)
df

Name Age  Salary
0  Vivek  22   30000
1    Max  44   60000

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
a=np.arange(1,32,1)
b=np.arange(1,11,1)
c={'day':a,'month':'jan','year':2023}
d={'day':b,'month':'feb','year':2023}
e=pd.DataFrame(c)
f=pd.DataFrame(d)

g=pd.concat([e,f])
g

day month  year
0     1   jan  2023
1     2   jan  2023
2     3   jan  2023
3     4   jan  2023
4     5   jan  2023
5     6   jan  2023
6     7   jan  2023
7     8   jan  2023
8     9   jan  2023
9    10   jan  2023
10   11   jan  2023
11   12   jan  2023
12   13   jan  2023
13   14   jan  2023
14   15   jan  2023
15   16   jan  2023
16   17   jan  2023
17   18   jan  2023
18   19   jan  2023
19   20   jan  2023
20   21   jan  2023
21   22   jan  2023
22   23   jan  2023
23   24   jan  2023
24   25   jan  2023
25   26   jan  2023
26   27   jan  2023
27   28   jan  2023
28   29   jan  2023
29   30   jan  2023
30   31   jan  2023
0     1   feb  2023
1     2   feb  2023
2     3   feb  2023
3     4   feb  2023
4     5   feb  2023
5     6   feb  2023
6     7   feb  2023
7     8   feb  2023
8     9   feb  2023
9    10   feb  2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
c=pd.DataFrame(lists)
c

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24